name: Automatic Fortnite API Trigger

on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  build:
    environment: ENV_SECRET
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Running Scripts
        env:
          ENV_SECRET: ${{ secrets.FORTNITE_SECRET }} 
        run: |
          pip install -r requirements.txt
          python script.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated Fortnite"
          git push
