name: Automatic Fortnite API Trigger

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    environment: ENV_SECRET
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Install packages
        run: pip install -r requirements.txt
        
      - name: Run script
        env:
          ENV_SECRET: ${{ secrets.FORTNITE_SECRET }} 
        run: python script.py       

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated A350"
          git push
